import type { Condition } from '../../types/condition'
import { generateId } from '../../lib/ids'

export const DEFAULT_CONDITIONS: Condition[] = [
  {
    id: generateId(),
    name: 'Blinded',
    description: 'Cannot see. Attack rolls against the creature have advantage, and the creature\'s attack rolls have disadvantage.',
    durationType: 'session',
    isLibraryEntry: true,
  },
  {
    id: generateId(),
    name: 'Charmed',
    description: 'Cannot attack the charmer. The charmer has advantage on social ability checks against the creature.',
    durationType: 'session',
    isLibraryEntry: true,
  },
  {
    id: generateId(),
    name: 'Deafened',
    description: 'Cannot hear. Automatically fails any check requiring hearing.',
    durationType: 'session',
    isLibraryEntry: true,
  },
  {
    id: generateId(),
    name: 'Exhausted',
    description: 'Stacked condition with 6 levels of severity. Level 1: Disadvantage on ability checks. Level 2: Speed halved. Level 3: Disadvantage on attacks and saves. Level 4: Hit point maximum halved. Level 5: Speed reduced to 0. Level 6: Death.',
    durationType: 'permanent',
    isLibraryEntry: true,
  },
  {
    id: generateId(),
    name: 'Frightened',
    description: 'Disadvantage on ability checks and attack rolls while the source of fear is within line of sight. Cannot willingly move closer to the source.',
    durationType: 'session',
    isLibraryEntry: true,
  },
  {
    id: generateId(),
    name: 'Grappled',
    description: 'Speed becomes 0. Ends if the grappler is incapacitated or the creature is moved out of reach.',
    durationType: 'session',
    isLibraryEntry: true,
  },
  {
    id: generateId(),
    name: 'Incapacitated',
    description: 'Cannot take actions or reactions.',
    durationType: 'session',
    isLibraryEntry: true,
  },
  {
    id: generateId(),
    name: 'Invisible',
    description: 'Cannot be seen without special senses. Attack rolls against the creature have disadvantage, and the creature\'s attacks have advantage.',
    durationType: 'session',
    isLibraryEntry: true,
  },
  {
    id: generateId(),
    name: 'Paralyzed',
    description: 'Incapacitated and cannot move or speak. Automatically fails Strength and Dexterity saves. Attack rolls against have advantage. Any attack within 5 ft is a critical hit.',
    durationType: 'session',
    isLibraryEntry: true,
  },
  {
    id: generateId(),
    name: 'Petrified',
    description: 'Transformed into solid inanimate substance. Incapacitated, unaware of surroundings, and has resistance to all damage.',
    durationType: 'session',
    isLibraryEntry: true,
  },
  {
    id: generateId(),
    name: 'Poisoned',
    description: 'Disadvantage on attack rolls and ability checks.',
    durationType: 'session',
    isLibraryEntry: true,
  },
  {
    id: generateId(),
    name: 'Prone',
    description: 'Can only crawl or spend half movement to stand. Disadvantage on attack rolls. Attacks against have advantage within 5 ft, disadvantage beyond.',
    durationType: 'session',
    isLibraryEntry: true,
  },
  {
    id: generateId(),
    name: 'Restrained',
    description: 'Speed becomes 0. Attack rolls have disadvantage; attacks against have advantage. Disadvantage on Dexterity saves.',
    durationType: 'session',
    isLibraryEntry: true,
  },
  {
    id: generateId(),
    name: 'Stunned',
    description: 'Incapacitated, cannot move, and can only speak falteringly. Automatically fails Strength and Dexterity saves. Attack rolls against have advantage.',
    durationType: 'session',
    isLibraryEntry: true,
  },
  {
    id: generateId(),
    name: 'Unconscious',
    description: 'Incapacitated, cannot move or speak, unaware of surroundings. Drops held items and falls prone. Automatically fails Strength and Dexterity saves.',
    durationType: 'session',
    isLibraryEntry: true,
  },
  {
    id: generateId(),
    name: 'Concentrating',
    description: 'Maintaining a concentration spell. Taking damage requires a Constitution save to maintain concentration.',
    durationType: 'session',
    isLibraryEntry: true,
  },
  {
    id: generateId(),
    name: 'Bleeding',
    description: 'Losing hit points at the start of each turn. Can be stopped by magical healing or a successful medicine check.',
    durationType: 'rounds',
    isLibraryEntry: true,
  },
  {
    id: generateId(),
    name: 'Burning',
    description: 'On fire, taking fire damage at the start of each turn. Can be extinguished by dropping prone and using an action.',
    durationType: 'rounds',
    isLibraryEntry: true,
  },
  {
    id: generateId(),
    name: 'Frozen',
    description: 'Encased in ice or magically slowed by cold. Speed is halved and may be vulnerable to bludgeoning damage.',
    durationType: 'rounds',
    isLibraryEntry: true,
  },
  {
    id: generateId(),
    name: 'Hasted',
    description: 'Speed doubled, +2 AC, advantage on Dexterity saves, and an additional action each turn (for attack, dash, disengage, hide, or use object).',
    durationType: 'session',
    isLibraryEntry: true,
  },
  {
    id: generateId(),
    name: 'Slowed',
    description: 'Speed halved, -2 AC and Dexterity saves. Cannot take reactions. On its turn can take either an action or a bonus action, not both.',
    durationType: 'session',
    isLibraryEntry: true,
  },
]
